"""Allow monthly_price_cents to be nullable

Revision ID: 9938f98ac9b4
Revises: 
Create Date: 2024-11-21 16:40:48.053636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9938f98ac9b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_packages', schema=None) as batch_op:
        batch_op.alter_column('monthly_price_cents',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_packages', schema=None) as batch_op:
        batch_op.alter_column('monthly_price_cents',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
